[package]
name = "image_converter"
version = "0.1.0"
edition = "2021"
authors = "Rust Group B"
description = "A fast image converter with GUI support"

[dependencies]
image = "0.24"
rayon = "1.8"
eframe = "0.26"
rfd = "0.12" 